/**
 * Write docs/ACCESS.md — who can do what in PODIUM — from the code itself.
 *
 *   npm run docs:access            the shipped roles (committed with the code)
 *   npm run docs:access -- --live  the roles as they are in the database named
 *                                  by DATABASE_URL, written to
 *                                  docs/ACCESS.live.local.md (not committed)
 *
 * The document is generated, never hand-edited: the permission catalog, the
 * shipped roles and the test-account table are the only sources, so it cannot
 * drift from what the code checks. The rules that are not a permission key —
 * the floor posts, the score console, the wave buttons — are written here
 * next to the file that enforces each one, so a change to one is a change to
 * the other in the same review.
 *
 * BFT MENA edits the live roles on the Roles screen, so the shipped roles are
 * starting points; --live shows what a running system actually grants.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { PERMISSION_TREE, PERMISSIONS, permissionEntry, type PermissionPolicy } from "../src/lib/permissions/catalog.ts";
import { DEFAULT_ROLE_FOR, SYSTEM_ROLES, type SystemRoleDef } from "../src/lib/permissions/system-roles.ts";
import { TEST_ACCOUNTS, testAccountEmail } from "../src/lib/permissions/test-account-roles.ts";

type RoleRow = Pick<SystemRoleDef, "key" | "name" | "description" | "assignableBy" | "accountTypes" | "permissions">;

const POLICY: Record<PermissionPolicy, string> = {
  general: "everyone",
  role: "role",
  bftOnly: "BFT MENA only",
  fullAdminOnly: "Full access only",
};

const ACCOUNT_TYPE: Record<string, string> = {
  admin: "BFT MENA · Full access",
  staff: "BFT MENA · Limited (Partial) access",
  studio: "Gym / Studio",
  organiser: "Organiser (event staff)",
  competitor: "Athlete",
};

async function liveRoles(): Promise<RoleRow[]> {
  const { PrismaMariaDb } = await import("@prisma/adapter-mariadb");
  const { PrismaClient } = await import("../src/generated/prisma/client.ts");
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("--live needs DATABASE_URL (node --env-file=… scripts/access-doc.ts --live)");
  const prisma = new PrismaClient({ adapter: new PrismaMariaDb(url) });
  try {
    const rows = await prisma.accessRole.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] });
    return rows.map((row) => ({
      key: row.key,
      name: row.name,
      description: row.description ?? "",
      assignableBy: row.assignableBy,
      accountTypes: (Array.isArray(row.accountTypes) ? row.accountTypes : []) as SystemRoleDef["accountTypes"],
      permissions: (Array.isArray(row.permissions) ? row.permissions : []).filter(
        (key): key is SystemRoleDef["permissions"][number] => typeof key === "string" && !!permissionEntry(key)
      ),
    }));
  } finally {
    await prisma.$disconnect();
  }
}

const live = process.argv.includes("--live");
const roles: RoleRow[] = live ? await liveRoles() : SYSTEM_ROLES;
const lines: string[] = [];
const out = (...text: string[]) => lines.push(...text);

// ── Title ────────────────────────────────────────────────────────────────────
out(
  "# PODIUM — who can do what",
  "",
  `_Generated by \`npm run docs:access${live ? " -- --live" : ""}\` from \`src/lib/permissions/\` and the rules named below. Do not edit by hand — change the code and run it again._`,
  "",
  live
    ? "**This copy shows the roles as they are in the live database** (BFT MENA edits them on the Roles screen). It is not committed."
    : "The roles below are the ones PODIUM **ships with**. BFT MENA can change them on the Roles screen, so a running system may differ — `npm run docs:access -- --live` (with the database's environment loaded) writes the live picture.",
  "",
  "Contents: [How access is decided](#how-access-is-decided) · [Account types](#account-types) · [The roles](#the-roles) · [On the floor](#on-the-floor-zone-posts) · [Scores](#scores) · [Wave control](#wave-control) · [Test accounts](#test-accounts) · [Known limits](#known-limits) · [Permission matrix](#permission-matrix) · [Who may give each role](#who-may-give-each-role)",
  ""
);

// ── How access is decided ────────────────────────────────────────────────────
out(
  "## How access is decided",
  "",
  "Two questions, answered separately:",
  "",
  "- **What may this person do?** Their **permissions** — keys like `waveControl.control` — which come from the **roles** they hold. Every screen and every server action checks a key.",
  "- **Whose data may they touch?** Their **account type**. BFT MENA and organisers see every team; a gym sees only its own teams and people; an athlete sees only their own team.",
  "",
  "```",
  "effective permissions = (always-on ∪ roles ∪ personal grants) ∩ ceiling(account type) − personal locks",
  "```",
  "",
  "- **BFT MENA Full access** (`admin`) passes every check and holds no roles.",
  "- A person can hold **several roles**; their permissions add up. A person holding none gets the default role of their account type:"
);
for (const [type, key] of Object.entries(DEFAULT_ROLE_FOR)) {
  out(`  - ${ACCOUNT_TYPE[type] ?? type} → **${roles.find((role) => role.key === key)?.name ?? key}**`);
}
out(
  "- Per person, any permission can be **granted** or **locked** (Users → the person → Access). A lock always wins.",
  "- A sign-up still **waiting for approval** gets only the always-on pages, whatever roles it carries.",
  "- **Policies** decide who can ever hold a key: _everyone_ — always on for every signed-in account; _role_ — given by roles and grants; _BFT MENA only_ — never reaches a gym, organiser or athlete account, even if a role they hold lists it; _Full access only_ — never given to anyone (correcting or unlocking a submitted score).",
  "- **Anti-escalation** (`src/lib/permissions/grant-policy.ts`):",
  "  - you can only hand out what you hold (Full access exempt), and nobody changes their own access;",
  "  - a BFT MENA Limited account manages another Limited account only if it holds everything that account holds — otherwise changing a stronger colleague's email and sending a reset link would take their account over;",
  "  - a gym gives only roles marked \"BFT MENA and studios\" (Athlete, Judge), only to its own people;",
  "  - a role is given only to the account types it is meant for (the Judge role to an organiser account, never to an athlete); it can always be taken away;",
  "  - `src/lib/access.ts` is where the scope rules live (`teamScope`, `accountScope`, `canWriteScore`, `canControlWave`).",
  "- Every competition console screen checks its key **and** that the viewer is not a gym or athlete account (`requireConsoleAccess`, `src/lib/session.ts`) — a layout alone is not a guard.",
  ""
);

// ── Account types ────────────────────────────────────────────────────────────
out(
  "## Account types",
  "",
  "| Account type | Sees | Lands on after sign-in | Notes |",
  "| --- | --- | --- | --- |",
  "| **BFT MENA · Full access** (`admin`) | everything | `/` dashboard | Holds no roles and needs none. The only account that corrects or unlocks a submitted score, and the only one that makes another Full access account. |",
  "| **BFT MENA · Limited access** (`staff`) | every team and every account | `/` if its roles open the dashboard, else `/home` | The only non-admin type that can hold BFT-MENA-only keys and use the score console. Never blocked by registration deadlines. |",
  "| **Gym / Studio** (`studio`) | its own studio's teams and people only | `/studio` | Registers, pairs and places its own teams; approves sign-ups that name it; gives Athlete and Judge roles to its own people. Never scores. |",
  "| **Organiser** (`organiser`) | every team (read) | `/home` | Used for event staff: organisers, judges, volunteers, coaches. What they can do is exactly their roles. Never holds a BFT-MENA-only key. |",
  "| **Athlete** (`competitor`) | their own team only | `/me` | Their profile, partner, team and wave. |",
  "",
  "Anyone with a **zone post** on a running competition (see [On the floor](#on-the-floor-zone-posts)) lands on their judge sheet, `/my-wave`, instead — with links back to their home and to the live board.",
  ""
);

// ── The roles, one by one ────────────────────────────────────────────────────
const always = PERMISSIONS.filter((entry) => entry.policy === "general");
out(
  "## The roles",
  "",
  `Every signed-in account also has the always-on pages: ${always.map((entry) => `${entry.screenLabel}`).join(", ")}.`,
  ""
);
for (const role of roles) {
  out(`### ${role.name}`, "");
  if (role.description) out(role.description, "");
  out(
    `- **Given by:** ${role.assignableBy === "bft_studio" ? "BFT MENA and studios" : "BFT MENA only"}`,
    `- **Meant for:** ${role.accountTypes.length ? role.accountTypes.map((type) => ACCOUNT_TYPE[type] ?? type).join(", ") : "any account type"}`,
    ""
  );
  const held = new Set<string>(role.permissions);
  const screens = PERMISSION_TREE.flatMap((module) =>
    module.screens
      .map((screen) => ({
        module: module.label,
        screen: screen.label,
        actions: screen.permissions.filter((entry) => entry.policy !== "general" && held.has(entry.key)),
      }))
      .filter((screen) => screen.actions.length)
  );
  if (!screens.length) {
    out("_No permissions of its own — only the always-on pages._", "");
    continue;
  }
  out("| Area | Screen | Can |", "| --- | --- | --- |");
  for (const screen of screens) {
    const can = screen.actions
      .map((entry) => `${entry.label}${entry.policy === "bftOnly" ? " _(BFT MENA accounts only)_" : ""}`)
      .join("; ");
    out(`| ${screen.module} | ${screen.screen} | ${can} |`);
  }
  out("");
}

// ── On the floor ─────────────────────────────────────────────────────────────
out(
  "## On the floor: zone posts",
  "",
  "Floor work is not only roles: it is a **post** on a zone of one competition (`ZoneStaff`). Posts are set on **Wave control → Zone teams** by whoever holds `zoneStaff.assign` (the Organiser role, BFT MENA). Only people whose roles carry the judge sheet — `judgeSheet.view` and `scores.enter`, i.e. the **Judge** role — can be put on a zone. A post opens nothing once its holder loses the Judge role.",
  "",
  "| Post | Scores | Also | Rule in |",
  "| --- | --- | --- | --- |",
  "| **Zone leader** (one per zone) | any station of their zone | places the zone's judges on stations (from their sheet); **starts the next wave** (Start only) | `zone-score-rules.ts`, `access.ts › canControlWave`, `actions/zone-staff.ts` |",
  "| **Judge** | the team on their own station, their own zone | — | `zone-score-rules.ts` |",
  "| **Reserve** | same as a judge, once placed on a station | — | `zone-score-rules.ts` |",
  "",
  "A judge or leader can write a zone only when **all** of these hold (`src/lib/zone-score-rules.ts`):",
  "",
  "1. the competition is **Running**;",
  "2. the team's wave has **reached that zone** (its work there has begun) — or is complete;",
  "3. the zone is **not submitted** yet for that team (a submitted zone is locked);",
  "4. the competition's **score-entry cut-off** has not passed;",
  "5. a judge (not a leader) has been **placed on a station**, and it is the team's station.",
  "",
  "Submitting a zone locks it. The sheet keeps the last three waves' unsubmitted teams, so a late submit can still be finished.",
  ""
);

// ── Scores ───────────────────────────────────────────────────────────────────
out(
  "## Scores",
  "",
  "| Where | Who | What |",
  "| --- | --- | --- |",
  "| **Judge sheet** `/my-wave` | judges and zone leaders (see above) | one zone of one team at a time |",
  "| **Score console** Competition → Score entry | BFT MENA Full; BFT MENA Limited with `scores.enter` | a whole team at once. Every zone the save leaves **complete** is submitted and locked; a zone still missing a value stays open for its judges. A zone a judge already submitted is never rewritten. |",
  "| **Corrections** | BFT MENA Full access only | *Unlock for correction* returns a submitted score to draft; nobody else can be given `scores.correct` or `scores.unlock`. |",
  "",
  "- Organisers, judges, gyms and athletes **never** write from the console, whatever keys they hold (`canWriteScore`, `src/lib/access.ts`). The Judge role holds `scores.enter` for the floor; it does not open the console.",
  "- After a wave's clock ends, the console is closed for everyone but Full access; judges may still finish an unsubmitted zone from their sheet until the score-entry cut-off.",
  "- **Finisher (last zone) time** is what the wave clock had left when the team finished, and never more than one zone's work time (`finisherRemainingMs`, `src/lib/floor.ts`). The Stop button opens only when the last zone begins; ending a wave early records 0:00 for teams that never reached the finisher.",
  ""
);

// ── Wave control ─────────────────────────────────────────────────────────────
out(
  "## Wave control",
  "",
  "| Button | Who | Rule in |",
  "| --- | --- | --- |",
  "| **Start the competition** (Scheduled → Running) | the supervisor: `waveControl.control` (Organiser role, BFT MENA) — or BFT MENA from Settings | `actions/waves.ts › startCompetitionDay` |",
  "| **Start wave** | the supervisor, or any **zone leader** of that competition | `access.ts › canControlWave` |",
  "| **End now** / **Reset** | the supervisor only | `access.ts › canControlWave` |",
  "| Put judges on zones, pick leaders | `zoneStaff.assign` | `actions/zone-staff.ts` |",
  "| Place judges on stations | `zoneStaff.assign`, or that zone's leader | `actions/zone-staff.ts` |",
  "| Rig screens (`/series/…/zone/N/stations`) before the day | BFT MENA, and `waveControl.view` holders (to set them up) | `visibility.ts › readsWholeBoard` |",
  "",
  "A new wave starts only once Zone 1 is free, so two waves never meet in a zone. Nothing changes the floor of a **finished** competition.",
  ""
);

// ── Test accounts ────────────────────────────────────────────────────────────
out(
  "## Test accounts",
  "",
  "One account per role, to walk the app as that role. BFT MENA Full access has none — that is BFT MENA's own login.",
  "",
  "| Email | Account type | Roles | Post | Try |",
  "| --- | --- | --- | --- | --- |"
);
for (const def of TEST_ACCOUNTS) {
  const roleNames = def.roles.map((key) => roles.find((role) => role.key === key)?.name ?? key).join(", ");
  out(
    `| \`${testAccountEmail(def.slug)}\` | ${ACCOUNT_TYPE[def.accountType] ?? def.accountType} | ${roleNames} | ${def.post === "leader" ? "Zone leader" : def.post === "judge" ? "Judge, station 1" : "—"} | ${def.purpose} |`
  );
}
out(
  "",
  "- **Password:** never written in this repository (it is public). It is set when the accounts are created and kept by BFT MENA.",
  "- **No emailed code, no email at all:** the addresses are listed in the server's `TEST_ACCOUNT_EMAILS`, which makes a password the whole sign-in and stops every email to them (`src/lib/test-accounts.ts`). They are not real mailboxes.",
  "- **On / off:** Block them on the Users screen between test sessions — a blocked account cannot sign in at all — or run the script with `--block` / `--unblock`.",
  "- **Create or reset** (on the live host, with its environment):",
  "",
  "  ```bash",
  "  TEST_ACCOUNT_PASSWORD='<password>' node --env-file=/opt/podium/.env scripts/test-accounts.mjs --production --place <competition-slug>",
  "  ```",
  "",
  "  It creates missing accounts and resets existing ones to exactly their roles, with no personal grants or locks. `--place` puts the zone leader and the judge on the first zone of that competition that has no leader. The gym account belongs to the empty sandbox studio **Test**, so it sees no real gym's data.",
  "- What a test account may do is exactly its account type and roles — the same checks as everyone else.",
  ""
);

// ── Known limits ─────────────────────────────────────────────────────────────
out(
  "## Known limits",
  "",
  "Decisions the code makes on purpose, or has not made yet:",
  "",
  "- **Organisers are not tied to one competition.** An organiser account's roles apply to every competition. Give the Organiser role only to people who run the floor for BFT MENA; it is BFT-MENA-only to hand out.",
  "- **An organiser can put themselves on a zone** (they hold `zoneStaff.assign`). Every change is in the audit log.",
  "- **Going Running is the only status change the floor makes.** Back to Scheduled, and Finished, stay in Settings (`settings.edit`, BFT MENA).",
  "- **Payment** stays BFT MENA's (`registrations.payment`); check-in is its own key, `registrations.attendance`, which the Organiser role carries.",
  "- **Registering a pair by hand** and **restoring a withdrawn team** are BFT MENA's (the CRM is where entries come from).",
  "- **The live roles can differ** from the shipped ones above — BFT MENA edits them on the Roles screen. Run with `--live` to see them.",
  ""
);

// ── The full matrix ──────────────────────────────────────────────────────────
out("## Permission matrix", "");
const header = ["Screen", "Action", "Key", "Policy", ...roles.map((role) => role.name)];
out(`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`);
for (const group of PERMISSION_TREE) {
  out(`| **${group.label}** | | | | ${roles.map(() => "").join(" | ")} |`);
  for (const screen of group.screens) {
    for (const entry of screen.permissions) {
      const cells = roles.map((role) =>
        entry.policy === "general" ? "·" : (role.permissions as string[]).includes(entry.key) ? "✓" : ""
      );
      out(`| ${screen.label} | ${entry.label} | \`${entry.key}\` | ${POLICY[entry.policy]} | ${cells.join(" | ")} |`);
    }
  }
}
out("", "`·` always on for everyone signed in.", "");

// ── Who may give each role ───────────────────────────────────────────────────
out("## Who may give each role", "", "| Role | Given by | Meant for |", "| --- | --- | --- |");
for (const role of roles) {
  out(
    `| ${role.name} | ${role.assignableBy === "bft_studio" ? "BFT MENA and studios" : "BFT MENA"} | ${role.accountTypes.length ? role.accountTypes.map((type) => ACCOUNT_TYPE[type] ?? type).join(", ") : "any"} |`
  );
}
out("");

const file = path.join(process.cwd(), "docs", live ? "ACCESS.live.local.md" : "ACCESS.md");
writeFileSync(file, lines.join("\n"));
console.info(`[docs] wrote ${file}`);
