/**
 * Write docs/ACCESS.md — who can do what in PODIUM — from the code itself.
 *
 *   npm run docs:access            the shipped roles (committed with the code)
 *   npm run docs:access -- --live  the roles as they are in the database named
 *                                  by DATABASE_URL, written to
 *                                  docs/ACCESS.live.local.md (not committed)
 *
 * The document is generated, never hand-edited: the permission catalog, the
 * shipped roles and the test-account table are the only sources, so it cannot
 * drift from what the code checks. The rules that are not a permission key —
 * the floor posts, the score console, the wave buttons — are written here
 * next to the file that enforces each one, so a change to one is a change to
 * the other in the same review.
 *
 * BFT MENA edits the live roles on the Roles screen, so the shipped roles are
 * starting points; --live shows what a running system actually grants.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { PERMISSION_TREE, PERMISSIONS, permissionEntry, type PermissionPolicy } from "../src/lib/permissions/catalog.ts";
import { DEFAULT_ROLE_FOR, SYSTEM_ROLES, type SystemRoleDef } from "../src/lib/permissions/system-roles.ts";
import { TEST_ACCOUNTS, testAccountEmail } from "../src/lib/permissions/test-account-roles.ts";

type RoleRow = Pick<SystemRoleDef, "key" | "name" | "description" | "assignableBy" | "accountTypes" | "permissions">;

const POLICY: Record<PermissionPolicy, string> = {
  general: "everyone",
  role: "role",
  bftOnly: "BFT MENA only",
  fullAdminOnly: "Full access only",
};

const ACCOUNT_TYPE: Record<string, string> = {
  admin: "BFT MENA · Full access",
  staff: "BFT MENA · Limited (Partial) access",
  studio: "Gym / Studio",
  organiser: "Organiser (event staff)",
  competitor: "Athlete",
};

async function liveRoles(): Promise<RoleRow[]> {
  const { PrismaMariaDb } = await import("@prisma/adapter-mariadb");
  const { PrismaClient } = await import("../src/generated/prisma/client.ts");
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("--live needs DATABASE_URL (node --env-file=… scripts/access-doc.ts --live)");
  const prisma = new PrismaClient({ adapter: new PrismaMariaDb(url) });
  try {
    const rows = await prisma.accessRole.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] });
    return rows.map((row) => ({
      key: row.key,
      name: row.name,
      description: row.description ?? "",
      assignableBy: row.assignableBy,
      accountTypes: (Array.isArray(row.accountTypes) ? row.accountTypes : []) as SystemRoleDef["accountTypes"],
      permissions: (Array.isArray(row.permissions) ? row.permissions : []).filter(
        (key): key is SystemRoleDef["permissions"][number] => typeof key === "string" && !!permissionEntry(key)
      ),
    }));
  } finally {
    await prisma.$disconnect();
  }
}

const live = process.argv.includes("--live");
const roles: RoleRow[] = live ? await liveRoles() : SYSTEM_ROLES;
const lines: string[] = [];
const out = (...text: string[]) => lines.push(...text);

// ── Title ────────────────────────────────────────────────────────────────────
out(
  "# PODIUM — who can do what",
  "",
  `_Generated by \`npm run docs:access${live ? " -- --live" : ""}\` from \`src/lib/permissions/\` and the rules named below. Do not edit by hand — change the code and run it again._`,
  "",
  live
    ? "**This copy shows the roles as they are in the live database** (BFT MENA edits them on the Roles screen). It is not committed."
    : "The roles below are the ones PODIUM **ships with**. BFT MENA can change them on the Roles screen, so a running system may differ — `npm run docs:access -- --live` (with the database's environment loaded) writes the live picture.",
  "",
  "Contents: [Who does what, in plain words](#who-does-what-in-plain-words) · [How access is decided](#how-access-is-decided) · [Account types](#account-types) · [The roles](#the-roles) · [On the floor](#on-the-floor-zone-posts) · [Scores](#scores) · [Wave control](#wave-control) · [Test accounts](#test-accounts) · [The desks of the day](#the-desks-of-the-day) · [Known limits](#known-limits) · [Permission matrix](#permission-matrix) · [Who may give each role](#who-may-give-each-role)",
  ""
);

// ── Who does what, in plain words ────────────────────────────────────────────
out(
  "## Who does what, in plain words",
  "",
  "A **role** says what a person can do; a **post** (Zone leader / Judge / Reserve, set on Wave control → Zone teams) says where they stand on the floor of one competition. One person can hold several roles; they add up.",
  "",
  "| Who | Screens, and what they can do there | Cannot |",
  "| --- | --- | --- |",
  "| **BFT MENA Full access** | Everything. The only one who corrects or unlocks a submitted score, changes an account type or which gym a gym account runs, creates BFT MENA or gym accounts, and decides who may give a role. | — |",
  "| **BFT MENA Partial** | The office's working set, as on the live Roles screen: **Registrations** end to end (create, edit, pair, withdraw, payment, the waiting list, export); **Users** (invite, edit, disable, delete, give roles, per-person overrides) and **Roles**; **Approvals**; competitions, studios, sponsors and **Settings**; **Score entry**; **Wave control** and zone teams; publishing results; the audit log; and the day's desks — **Entrance check-in**, **Warm-up check-in**, and changing a team's category or level at the athlete's request (any level, Pro included). | Correct or unlock a submitted score; change account types; create BFT MENA or gym accounts; change a stronger person's email or send them a reset link |",
  "| **Gym / Studio** | **Users:** invite its athletes and event staff, approve sign-ups that name it, give Athlete / Judge to its own people. **Registrations:** its own teams (edit, withdraw, pair; category or level at the athlete's request). **Entrance check-in / Warm-up check-in:** its own teams. **Waves:** view. **Scores / Results:** its own teams. **Announcements:** to its own people. | Wave control, Marshalling, payment, other gyms' data before the day; any floor button even if a role lists it |",
  "| **Organiser** (floor supervisor) | **Wave control:** start the day (on the competition's date), Start / End now / Reset a wave (Reset is refused once a zone of that wave is submitted); rig-screen links. **Entrance check-in:** each athlete or a whole team. **Warm-up check-in:** mark teams ready, wave by wave. **Marshalling:** view, check teams in. **Waves:** set the category schedule, create waves, set times, auto-assign, move a team by hand (it then runs manually) or return it to Auto Assign. **Zone teams:** put judges on zones, pick leaders, place stations. **Registrations:** view, check in, export (no money, no phone or email); create, edit and pair teams; change a team's category or level at the athlete's request. **Approvals, competitions, studios:** view. **T-shirts:** counts and list. **Scores / Results / Settings:** view. | Payment and the waiting list (BFT-only keys an organiser account never holds, though the role lists them), settings, the score console, corrections |",
  "| **Zone leader** (post) | **Judge sheet:** the zone's whole day, every station; scores any station once the wave reaches the zone; submits sheets a judge left open; places the zone's judges on stations; **Start** the next wave when Zone 1 is free. | End now / Reset; other zones |",
  "| **Judge** (post) | **Judge sheet:** \"You are on Zone Y · Station X\"; every wave coming to that station today with the team, the athletes and whether they checked in; the next one highlighted with a countdown — before it starts. Scores **only** that station, only while the wave is in the zone. | Score before the wave arrives, after the next one comes, or another station; the console; either check-in desk; changing a team's category or level |",
  "| **Reserve** (post) | Until placed: the zone's whole day, every station, read-only. Once placed on a station: the same as a Judge. | Score before being placed |",
  "| **Volunteer** | **Marshalling:** where each wave is, where it goes next, who to call up — station by station, with names. **Entrance check-in** and **Warm-up check-in:** every team. Changes a team's category or level at the athlete's request. **Waves:** view. Live board. | Start or stop waves, score, change who is on a team, anything else |",
  "| **Coach** | **Waves** and **Results**: view. Live board. | Everything else |",
  "| **Athlete** | **My team (`/me`):** team, partner, wave, **station**, **time in each zone** (estimated until the wave starts), check-in status, T-shirt size of each seat; **change their team's category or level** (Rookie ↔ Open) until the competition's team-change cutoff (24 hours before, by default); ask for a morning / midday / evening wave. **My wave**, Results, Live board, Find a partner. | See other teams before the day; anything on the staff side |",
  "",
);

// ── How access is decided ────────────────────────────────────────────────────
out(
  "## How access is decided",
  "",
  "Two questions, answered separately:",
  "",
  "- **What may this person do?** Their **permissions** — keys like `waveControl.control` — which come from the **roles** they hold. Every screen and every server action checks a key.",
  "- **Whose data may they touch?** Their **account type**. BFT MENA and organisers see every team; a gym sees only its own teams and people; an athlete sees only their own team.",
  "",
  "```",
  "effective permissions = (always-on ∪ roles ∪ personal grants) ∩ ceiling(account type) − personal locks",
  "```",
  "",
  "- **BFT MENA Full access** (`admin`) passes every check and holds no roles.",
  "- A person can hold **several roles**; their permissions add up. A person holding none gets the default role of their account type:"
);
for (const [type, key] of Object.entries(DEFAULT_ROLE_FOR)) {
  out(`  - ${ACCOUNT_TYPE[type] ?? type} → **${roles.find((role) => role.key === key)?.name ?? key}**`);
}
out(
  "- Per person, any permission can be **granted** or **locked** (Users → the person → Access). A lock always wins.",
  "- A sign-up still **waiting for approval** gets only the always-on pages, whatever roles it carries.",
  "- **Policies** decide who can ever hold a key: _everyone_ — always on for every signed-in account; _role_ — given by roles and grants; _BFT MENA only_ — never reaches a gym, organiser or athlete account, even if a role they hold lists it; _Full access only_ — never given to anyone (correcting or unlocking a submitted score).",
  "- **Anti-escalation** (`src/lib/permissions/grant-policy.ts`):",
  "  - you can only hand out what you hold (Full access exempt), and nobody changes their own access;",
  "  - a BFT MENA Limited account manages another Limited account only if it holds everything that account holds — otherwise changing a stronger colleague's email and sending a reset link would take their account over;",
  "  - changing **anyone's** email or sending them a reset link needs every competition and platform power that person holds (`canTakeOverTarget`) — an athlete's own pages don't count;",
  "  - only Full access changes an account type, moves a gym account to another gym, creates a BFT MENA or gym account, or changes who may give a role and to which account types;",
  "  - a gym gives only roles marked \"BFT MENA and studios\" (Athlete, Judge), only to its own people;",
  "  - a role is given only to the account types it is meant for (the Judge role to an organiser account, never to an athlete); it can always be taken away;",
  "  - `src/lib/access.ts` is where the scope rules live (`teamScope`, `accountScope`, `canWriteScore`, `canControlWave`).",
  "- Every competition console screen checks its key **and** that the viewer is not a gym or athlete account (`requireConsoleAccess`, `src/lib/session.ts`) — a layout alone is not a guard.",
  ""
);

// ── Account types ────────────────────────────────────────────────────────────
out(
  "## Account types",
  "",
  "| Account type | Sees | Lands on after sign-in | Notes |",
  "| --- | --- | --- | --- |",
  "| **BFT MENA · Full access** (`admin`) | everything | `/` dashboard | Holds no roles and needs none. The only account that corrects or unlocks a submitted score, and the only one that makes another Full access account. On a team's registration form, corrects the team name and any athlete's name and email at any time — the same athlete, who keeps their account, waiver and check-in; for an athlete with an account, their sign-in email changes too, on a confirming tick (someone else in the seat is a Swap). |",
  "| **BFT MENA · Limited access** (`staff`) | every team and every account | `/` if its roles open the dashboard, else `/home` | The only non-admin type that can hold BFT-MENA-only keys and use the score console. Never blocked by registration deadlines. |",
  "| **Gym / Studio** (`studio`) | its own studio's teams and people only | `/studio` | Registers, pairs and places its own teams; approves sign-ups that name it; gives Athlete and Judge roles to its own people. Never scores. |",
  "| **Organiser** (`organiser`) | every team (read) | `/home` | Used for event staff: organisers, judges, volunteers, coaches. What they can do is exactly their roles. Never holds a BFT-MENA-only key. |",
  "| **Athlete** (`competitor`) | their own team only | `/me` | Their profile, partner, team and wave. |",
  "",
  "Anyone with a **zone post** on a running competition (see [On the floor](#on-the-floor-zone-posts)) lands on their judge sheet, `/my-wave`, instead — with links back to their home and to the live board.",
  ""
);

// ── The roles, one by one ────────────────────────────────────────────────────
const always = PERMISSIONS.filter((entry) => entry.policy === "general");
out(
  "## The roles",
  "",
  `Every signed-in account also has the always-on pages: ${always.map((entry) => `${entry.screenLabel}`).join(", ")}.`,
  ""
);
for (const role of roles) {
  out(`### ${role.name}`, "");
  if (role.description) out(role.description, "");
  out(
    `- **Given by:** ${role.assignableBy === "bft_studio" ? "BFT MENA and studios" : "BFT MENA only"}`,
    `- **Meant for:** ${role.accountTypes.length ? role.accountTypes.map((type) => ACCOUNT_TYPE[type] ?? type).join(", ") : "any account type"}`,
    ""
  );
  const held = new Set<string>(role.permissions);
  const screens = PERMISSION_TREE.flatMap((module) =>
    module.screens
      .map((screen) => ({
        module: module.label,
        screen: screen.label,
        actions: screen.permissions.filter((entry) => entry.policy !== "general" && held.has(entry.key)),
      }))
      .filter((screen) => screen.actions.length)
  );
  if (!screens.length) {
    out("_No permissions of its own — only the always-on pages._", "");
    continue;
  }
  out("| Area | Screen | Can |", "| --- | --- | --- |");
  for (const screen of screens) {
    const can = screen.actions
      .map((entry) => `${entry.label}${entry.policy === "bftOnly" ? " _(BFT MENA accounts only)_" : ""}`)
      .join("; ");
    out(`| ${screen.module} | ${screen.screen} | ${can} |`);
  }
  out("");
}

// ── On the floor ─────────────────────────────────────────────────────────────
out(
  "## On the floor: zone posts",
  "",
  "Floor work is not only roles: it is a **post** on a zone of one competition (`ZoneStaff`). Posts are set on **Wave control → Zone teams** by whoever holds `zoneStaff.assign` (the Organiser role, BFT MENA). Only people whose roles carry the judge sheet — `judgeSheet.view` and `scores.enter`, i.e. the **Judge** role — can be put on a zone. A post opens nothing once its holder loses the Judge role.",
  "",
  "| Post | Scores | Also | Rule in |",
  "| --- | --- | --- | --- |",
  "| **Zone leader** (one or more per zone) | any station of their zone, for any wave that reached it — including a sheet a judge left open | places the zone's judges on stations (from their sheet); **starts the next wave** (Start only) | `zone-score-rules.ts`, `access.ts › canControlWave`, `actions/zone-staff.ts` |",
  "| **Judge** | only the team on their own station, in the wave their zone is **on** | — | `zone-score-rules.ts`, `floor.ts › zoneDuty` |",
  "| **Reserve** | same as a judge, once placed on a station | — | `zone-score-rules.ts` |",
  "",
  "### What a judge sees, and when",
  "",
  "At the top the sheet says where the judge stands (\"You are on Zone Y · Station X\") and lists **their day**: every wave that will come through the zone, the team it brings to their station, the athletes' names, whether the pair checked in, and roughly when it arrives — the next one highlighted with a countdown (`judge-day.ts`, `floor.ts › zoneSchedule`). It is there **before a wave starts, and before the competition starts**, so the judge can call the pair over during the changeover. Times of a wave not started yet are estimates: its planned start, pushed later when the floor runs behind. A gym's own account judging sees team numbers but not names until the competition is Running. A leader, or a judge not yet placed on a station, sees every station of the zone.",
  "",
  "Below that, the **scoring card** shows **one team**: the one on the judge's station, in the wave the judge's zone is **on** — the last wave that has reached that zone (`floor.ts › waveOnDuty`). The screen and the server use the same rule, so nothing can be written that the sheet does not show.",
  "",
  "| Moment (Zone N) | The judge sees |",
  "| --- | --- |",
  "| Competition not Running | the day's list; scoring \"opens when the competition starts\". |",
  "| Not placed on a station | every station of the zone in the day's list; \"Waiting for your zone leader to place you on a station.\" |",
  "| No wave has reached Zone N | \"No team on your zone or station right now\" — and, if a wave is on the floor, which one and **when it reaches Zone N** (a countdown). |",
  "| A wave is working in Zone N, or changing zones after it | the station's team, with the zone timer. \"No team on your station in this wave\" if the wave has none there. |",
  "| That wave has moved on, sheet not submitted | the team stays, marked \"has left your zone — submit before the next wave arrives\". |",
  "| That wave has moved on, sheet submitted | \"No team on your zone or station right now\", and when the next wave arrives. |",
  "| The next wave reaches Zone N | its team replaces the last one. A sheet still open from the last wave is closed for the judge; **the zone leader** (or BFT MENA in the console) submits it. |",
  "",
  "A wave appears on the sheet **by itself**: the sheet re-reads every 5 seconds, and exactly when the clock brings a wave into the zone. A wave ended early (End now) never reaches the zones it had not started — those zones never see its teams.",
  "",
  "A judge or leader can write a zone only when **all** of these hold (`src/lib/zone-score-rules.ts`):",
  "",
  "1. the competition is **Running**;",
  "2. the team's wave has **reached that zone** (its work there began, before any early end);",
  "3. for a judge or reserve: that wave is the one the zone is **on** (not one it has moved on from);",
  "4. the zone is **not submitted** yet for that team (a submitted zone is locked);",
  "5. the competition's **score-entry cut-off** has not passed;",
  "6. a judge (not a leader) has been **placed on a station**, and it is the team's station.",
  ""
);

// ── Scores ───────────────────────────────────────────────────────────────────
out(
  "## Scores",
  "",
  "| Where | Who | What |",
  "| --- | --- | --- |",
  "| **Judge sheet** `/my-wave` | judges and zone leaders (see above) | one zone of one team at a time |",
  "| **Score console** Competition → Score entry | BFT MENA Full; BFT MENA Limited with `scores.enter` | a whole team at once. Every zone the save leaves **complete** is submitted and locked; a zone still missing a value stays open for its judges. A zone a judge already submitted is never rewritten. |",
  "| **Corrections** | BFT MENA Full access only | *Unlock for correction* returns a submitted score to draft; nobody else can be given `scores.correct` or `scores.unlock`. |",
  "",
  "- Organisers, judges, gyms and athletes **never** write from the console, whatever keys they hold (`canWriteScore`, `src/lib/access.ts`). The Judge role holds `scores.enter` for the floor; it does not open the console.",
  "- After a wave's clock ends, the console is closed for everyone but Full access. A judge can still submit the last wave's open sheet until the next wave reaches their zone; the zone leader can submit any open sheet of their zone until the score-entry cut-off.",
  "- **Finisher (last zone) time** is what the wave clock had left when the team finished, and never more than one zone's work time (`finisherRemainingMs`, `src/lib/floor.ts`). The Stop button opens only when the last zone begins; ending a wave early records 0:00 for teams that never reached the finisher.",
  ""
);

// ── Wave control ─────────────────────────────────────────────────────────────
out(
  "## Wave control",
  "",
  "| Button | Who | Rule in |",
  "| --- | --- | --- |",
  "| **Start the competition** (Scheduled → Running) | `waveControl.control` (Organiser role) or `waveControl.startDay` — **only on the competition's date** unless BFT MENA; BFT MENA also from Settings | `actions/waves.ts › startCompetitionDay` |",
  "| **Start wave** | `waveControl.control` or `waveControl.start`, or any **zone leader** of that competition | `access.ts › canControlWave` |",
  "| **End now** | `waveControl.control` or `waveControl.end` | `access.ts › canControlWave` |",
  "| **Reset** | `waveControl.control` or `waveControl.reset` — refused once any zone of that wave is **submitted**, except for Full access | `access.ts › canControlWave`, `actions/waves.ts` |",
  "| **Marshalling** (`/series/…/marshalling`) | `marshalling.view` (Volunteer), or anyone who sees Wave control; the Check in button needs `registrations.attendance` (see [The desks of the day](#the-desks-of-the-day)) | `screens/marshalling.tsx`, `lib/marshalling.ts` |",
  "| **Category schedule** (Settings: each category's start and break) | `waves.edit` on a floor account (Organiser role, BFT MENA) | `access.ts › canBuildSchedule`, `actions/category-schedule.ts` |",
  "| **Auto-assign waves** (each category in its own block; teams running manually stay put), add / edit / remove a wave | `waves.edit` on a floor account | `access.ts › canBuildSchedule`, `actions/teams.ts`, `actions/waves.ts` |",
  "| **Move…** a team to another wave or station, or exchange places with the team on a chosen station (both then **run manually**), **Return to Auto Assign** | `waves.placeTeams` (Organiser role, BFT MENA) — never a judge or an athlete; a gym account's key reaches only its own teams, and its Waves screen has no such button | `access.ts › canPlaceTeams`, `actions/team-slot.ts` |",
  "| Put judges on zones, pick leaders | `zoneStaff.assign` | `actions/zone-staff.ts` |",
  "| Place judges on stations | `zoneStaff.assign`, or that zone's leader | `actions/zone-staff.ts` |",
  "| Rig screens (`/series/…/zone/N/stations`) before the day | BFT MENA, and `waveControl.view` holders (to set them up) | `visibility.ts › readsWholeBoard` |",
  "",
  "A new wave starts only once Zone 1 is free, so two waves never meet in a zone. Nothing changes the floor of a **finished** competition. Every wave button and every schedule change refuses a gym or athlete account, whatever a role they hold lists (`access.ts › isFloorAccount`). An idle rig screen shows who is **up next** on it, and when.",
  ""
);

// ── Test accounts ────────────────────────────────────────────────────────────
out(
  "## Test accounts",
  "",
  "One account per role, to walk the app as that role. BFT MENA Full access has none — that is BFT MENA's own login.",
  "",
  "| Email | Account type | Roles | Post | Try |",
  "| --- | --- | --- | --- | --- |"
);
for (const def of TEST_ACCOUNTS) {
  const roleNames = def.roles.map((key) => roles.find((role) => role.key === key)?.name ?? key).join(", ");
  out(
    `| \`${testAccountEmail(def.slug)}\` | ${ACCOUNT_TYPE[def.accountType] ?? def.accountType} | ${roleNames} | ${def.post === "leader" ? "Zone leader" : def.post === "judge" ? `Judge, station ${def.station ?? "—"}` : "—"} | ${def.purpose} |`
  );
}
out(
  "",
  "- **Password:** never written in this repository (it is public). It is set when the accounts are created and kept by BFT MENA.",
  "- **No emailed code, no email at all:** the addresses are listed in the server's `TEST_ACCOUNT_EMAILS`, which makes a password the whole sign-in and stops every email to them (`src/lib/test-accounts.ts`). They are not real mailboxes.",
  "- **On / off:** Block them on the Users screen between test sessions — a blocked account cannot sign in at all — or run the script with `--block` / `--unblock`.",
  "- **Create or reset** (on the live host, with its environment):",
  "",
  "  ```bash",
  "  TEST_ACCOUNT_PASSWORD='<password>' node --env-file=/opt/podium/.env scripts/test-accounts.mjs --production --place <competition-slug>",
  "  ```",
  "",
  "  It creates missing accounts and resets existing ones to exactly their roles, with no personal grants or locks. `--place` puts the zone leader and the judge on the first zone of that competition that has no leader. The gym account belongs to the empty sandbox studio **Test**, so it sees no real gym's data.",
  "- What a test account may do is exactly its account type and roles — the same checks as everyone else.",
  ""
);

// ── Known limits ─────────────────────────────────────────────────────────────
out(
  "## The desks of the day",
  "",
  "Three things done at a desk on the day, each an explicit key held through a role — the Organiser, Volunteer, Gym / Studio and BFT MENA Partial roles carry them; the **Judge**, **Coach** and **Athlete** roles do not. Nobody holds one merely for not being a judge, and an athlete's account never works a desk whatever it is given (`access.ts`). Whose teams a desk reaches is the account type's scope: BFT MENA and event staff every team, a gym its own.",
  "",
  "| What | Who | Rule in |",
  "| --- | --- | --- |",
  "| **Entrance check-in and check-out** (`/series/…/check-in`, a gym's at `/studio/…/check-in`) — arrival at the venue and departure, per athlete or per team, each athlete's waiver status (signed or not — never the signature); totals for teams and athletes, by category and level; search and filters | screen: `checkIn.view` or the action; action: `registrations.attendance` (or `registrations.payment`) | `access.ts › canCheckInEntrance`, `checkin-db.ts`, `screens/check-in.tsx` |",
  "| **Warm-up check-in and check-out** (`/series/…/warm-up`, `/studio/…/warm-up`) — ready to compete in the team's wave, one checklist per wave, with the entrance and waiver status beside it | screen: `checkIn.view` or the action; action: `checkIn.warmup` | `access.ts › canMarkWarmupReady`, `checkin-db.ts`, `screens/warm-up.tsx` |",
  "| **Waiver Declarations** (`/waivers`) — read the competition's waiver in English or Arabic and sign it; the receipt | the athlete, for themselves only — any signed-in account holding a seat (an organiser who also competes signs their own). Nobody signs for anybody else | `actions/waivers.ts › signMyWaiver`, `waivers/waiver-db.ts` |",
  "| **Settings → Waiver** — require a waiver version for a competition, read every signed record and receipt | `waivers.manage` (BFT MENA only) | `actions/waivers.ts › attachWaiver`, `components/waivers/waiver-settings.tsx` |",
  "| **Change a team's category or level for an athlete** — on the team's registration, on a gym's Teams tab, and on each team at the entrance desk | `registrations.bracket`, and only after confirming the athlete asked for it and approves | `access.ts › canAssistBracketChange`, `bracket-change.ts` |",
  "| **Change my own team's category or level** (`/me`) | the athlete, with `athleteHome.editTeam` — either member of the team | `bracket-change.ts` |",
  "",
  "- **Waiver, arrival and readiness are three facts, stored apart**: each athlete's own signature of the competition's current waiver (`WaiverAcceptance`), their arrival (`Competitor.attendedAt` / `Team.attendedAt`), and the team's readiness for its wave (`Team.warmupReadyAt` + `warmupWaveId`). **Entrance check-in** needs the athlete's signature, where the competition requires a waiver; a team check-in names who has not signed and checks nobody in. **Entrance check-out** records the departure (no signature needed) and takes back the team's readiness. **Warm-up check-in** needs every athlete signed and checked in, and a wave; **warm-up check-out** is always allowed. A team moved to another wave, or given a new member, warms up again. A team is checked in only when every athlete on it is; one of two is *partly arrived*, and the absent partner is not counted.",
  "- **Every check-in and check-out is kept** (`AttendanceEvent`: who, when, which athlete or wave) and audited; **pressing twice is one**: the first time stands, nothing is written again and only one audit line exists.",
  "- **Start wave** needs every athlete of every team in the wave signed, checked in and ready for that wave — for everybody, BFT MENA included; it lists who is missing what. The desks' keys never include starting a wave (see [Wave control](#wave-control)).",
  "- **Category and level**: Womens / Mens / Mixed — Womens cannot hold somebody registered as a man, nor Mens somebody registered as a woman; Rookie ↔ Open either way. Into or out of **Pro** is BFT MENA's. **When** is two clocks (`bracket.ts`): the **athlete and their gym** until the competition's own cutoff — *Settings → Team changes*, 24 hours before the start by default — and never once their wave has started; **BFT MENA and event staff** (Organiser, Volunteer) until a score has been entered for that team, even minutes before the start or with the wave already called. Nobody changes the bracket of a team that has a score, or of a finished competition. A team already placed keeps its wave and station; its check-in and readiness are untouched.",
  "- **Every change is in the audit log** (`registration.bracket_changed`): who, which team, from what to what, when, and whether the athlete did it or staff did it at the athlete's request.",
  ""
);

out(
  "## Known limits",
  "",
  "Decisions the code makes on purpose, or has not made yet:",
  "",
  "- **Organisers are not tied to one competition yet.** An organiser account's roles apply to every competition (per-competition roles are the next step). Until then: give floor roles only to this event's staff and take them away after, and an organiser can start a competition's day only on its date. Judges already are per competition — through their post.",
  "- **An organiser can put themselves on a zone** (they hold `zoneStaff.assign`). Every change is in the audit log.",
  "- **Going Running is the only status change the floor makes.** Back to Scheduled, and Finished, stay in Settings (`settings.edit`, BFT MENA).",
  "- **Payment** stays BFT MENA's (`registrations.payment`); entrance check-in is its own key, `registrations.attendance`, carried by the Organiser, Volunteer, Gym / Studio and BFT MENA Partial roles. The roster export leaves out money unless you hold `registrations.payment`, and phone / email unless you are BFT MENA or the athletes' own gym; every download is in the audit log.",
  "- **Registering a pair by hand** and **restoring a withdrawn team** are BFT MENA's (the CRM is where entries come from).",
  "- **An athlete's email is who their seat is** for everybody but BFT MENA Full access: below it, a new email on the registration form is a new person (the floor's barriers apply), and an athlete who has signed in keeps theirs (changed on their account, or a Swap). Full access corrects the same athlete's name and email — never onto another account's address, never its own; every change is in the audit log (`registration.updated`, and `account.updated` for a sign-in email).",
  "- **Each athlete has an Edit button on the team's page** (the console's and a gym's, for whoever holds `registrations.edit`): **Correct details** puts the same athlete right (name, email, phone, date of birth — nothing of theirs is cleared, check-in and warm-up stand), **Replace with another person** is a swap (`registrations.pair`). A signed-in athlete's name, email and phone are their account's: Full access only. **After team changes close** (24 hours before, and on the day) the organiser, the gym (its own teams) and BFT MENA Partial make either **at the athlete's request only**, on the tick the category change uses, written into the audit line; nobody new joins a team once its wave has started or it has a score.",
  "- **The live roles can differ** from the shipped ones above — BFT MENA edits them on the Roles screen. Run with `--live` to see them.",
  ""
);

// ── The full matrix ──────────────────────────────────────────────────────────
out("## Permission matrix", "");
const header = ["Screen", "Action", "Key", "Policy", ...roles.map((role) => role.name)];
out(`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`);
for (const group of PERMISSION_TREE) {
  out(`| **${group.label}** | | | | ${roles.map(() => "").join(" | ")} |`);
  for (const screen of group.screens) {
    for (const entry of screen.permissions) {
      const cells = roles.map((role) =>
        entry.policy === "general" ? "·" : (role.permissions as string[]).includes(entry.key) ? "✓" : ""
      );
      out(`| ${screen.label} | ${entry.label} | \`${entry.key}\` | ${POLICY[entry.policy]} | ${cells.join(" | ")} |`);
    }
  }
}
out("", "`·` always on for everyone signed in.", "");

// ── Who may give each role ───────────────────────────────────────────────────
out("## Who may give each role", "", "| Role | Given by | Meant for |", "| --- | --- | --- |");
for (const role of roles) {
  out(
    `| ${role.name} | ${role.assignableBy === "bft_studio" ? "BFT MENA and studios" : "BFT MENA"} | ${role.accountTypes.length ? role.accountTypes.map((type) => ACCOUNT_TYPE[type] ?? type).join(", ") : "any"} |`
  );
}
out("");

const file = path.join(process.cwd(), "docs", live ? "ACCESS.live.local.md" : "ACCESS.md");
writeFileSync(file, lines.join("\n"));
console.info(`[docs] wrote ${file}`);
