/**
 * Write docs/ACCESS.md from the permission catalog and the shipped roles.
 *
 *   npm run docs:access
 *
 * The document is generated, never hand-edited: the catalog is the only
 * vocabulary of access, so the matrix can never drift from what the code
 * actually checks. The shipped roles are starting points — BFT MENA edits the
 * live ones on the Roles screen — so the matrix shows the defaults.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { PERMISSION_TREE, type PermissionPolicy } from "../src/lib/permissions/catalog.ts";
import { DEFAULT_ROLE_FOR, SYSTEM_ROLES } from "../src/lib/permissions/system-roles.ts";

const POLICY: Record<PermissionPolicy, string> = {
  general: "everyone",
  role: "role",
  bftOnly: "BFT MENA only",
  fullAdminOnly: "Full access only",
};

const lines: string[] = [];
lines.push("# Access matrix");
lines.push("");
lines.push("_Generated by `npm run docs:access` from `src/lib/permissions/`. Do not edit by hand._");
lines.push("");
lines.push("## How access is decided");
lines.push("");
lines.push("```");
lines.push("effective = (general ∪ roles ∪ grants) ∩ ceiling(account type) − locks");
lines.push("```");
lines.push("");
lines.push("- **BFT MENA Full access** (`admin`) passes every check and holds no roles.");
lines.push("- A person can hold **several roles**; their permissions add up. A person holding none gets the default role for their account type:");
for (const [type, key] of Object.entries(DEFAULT_ROLE_FOR)) lines.push(`  - \`${type}\` → **${SYSTEM_ROLES.find((r) => r.key === key)?.name ?? key}**`);
lines.push("- Per person, any permission can be **granted** or **locked**. A lock always wins.");
lines.push("- **Policies**: _everyone_ — always on, even while waiting for approval; _role_ — given by roles and grants; _BFT MENA only_ — never reaches a studio, organiser or athlete account; _Full access only_ — never given to anyone.");
lines.push("- **Anti-escalation**: you can only give what you hold (Full access exempt); nobody changes their own access; a studio gives only roles marked \"studios can give\", only to its own people.");
lines.push("");
lines.push("## Default roles × permissions");
lines.push("");
const header = ["Screen", "Action", "Key", "Policy", ...SYSTEM_ROLES.map((role) => role.name)];
lines.push(`| ${header.join(" | ")} |`);
lines.push(`| ${header.map(() => "---").join(" | ")} |`);
for (const group of PERMISSION_TREE) {
  lines.push(`| **${group.label}** | | | | ${SYSTEM_ROLES.map(() => "").join(" | ")} |`);
  for (const screen of group.screens) {
    for (const entry of screen.permissions) {
      const cells = SYSTEM_ROLES.map((role) =>
        entry.policy === "general" ? "·" : (role.permissions as string[]).includes(entry.key) ? "✓" : ""
      );
      lines.push(`| ${screen.label} | ${entry.label} | \`${entry.key}\` | ${POLICY[entry.policy]} | ${cells.join(" | ")} |`);
    }
  }
}
lines.push("");
lines.push("`·` always on for everyone signed in.");
lines.push("");
lines.push("## Who may give each role");
lines.push("");
lines.push("| Role | Given by | Meant for | What it is for |");
lines.push("| --- | --- | --- | --- |");
for (const role of SYSTEM_ROLES) {
  lines.push(
    `| ${role.name} | ${role.assignableBy === "bft_studio" ? "BFT MENA and studios" : "BFT MENA"} | ${role.accountTypes.join(", ")} | ${role.description} |`
  );
}
lines.push("");

const out = path.join(process.cwd(), "docs", "ACCESS.md");
writeFileSync(out, lines.join("\n"));
console.info(`[docs] wrote ${out}`);
